name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./public
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build project
        working-directory: ./public
        run: npm run build 

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Angular-SPA
          path: ./public/dist

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: Angular-SPA
          path: jsswangular/browser

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_OTPT_777E0 }}
          projectId: test-1-cd7e8
          channelId: live
